// <auto-generated />
namespace EsportsTournamentManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class AddDragonsAndTowers : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "202606262330000_AddDragonsAndTowers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return null; }
        }
    }
}
